# Generated by Django 5.0.5 on 2024-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_enabled', models.BooleanField(default=True)),
                ('measurement_interval', models.IntegerField(help_text='Interval in seconds')),
                ('pump_enabled', models.BooleanField(default=True)),
                ('pump_duration', models.IntegerField(help_text='Duration in seconds')),
                ('max_consecutive_pumps', models.IntegerField(default=0)),
                ('moisture_threshold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MoistureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('moisture_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PumpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.BooleanField(default=False)),
            ],
        ),
    ]
