# Generated by Django 5.0.5 on 2024-05-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='valve_duration',
            field=models.IntegerField(default=7, help_text='Duration in seconds'),
            preserve_default=False,
        ),
    ]
