# Generated by Django 5.0.5 on 2026-06-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuration_valve_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='max_consecutive_pumps',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='moisture_threshold',
        ),
    ]
