# Generated by Django 5.0.5 on 2026-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_threshold_and_consecutive_pumps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('et0', models.FloatField(help_text='Reference evapotranspiration used (mm)')),
            ],
            options={
                'ordering': ['-schedule_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPumpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='calc_time',
            field=models.TimeField(default='06:00', help_text='Time of day the daily plan is computed'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='latitude',
            field=models.FloatField(default=47.3769, help_text='Latitude for the ET0 fetch'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='pump_seconds_per_mm',
            field=models.FloatField(default=10.0, help_text='Pump runtime in seconds needed per mm of ET0'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='longitude',
            field=models.FloatField(default=8.5417, help_text='Longitude for the ET0 fetch'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='window_end',
            field=models.TimeField(default='20:00', help_text='End of the watering window'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='window_start',
            field=models.TimeField(default='07:00', help_text='Start of the watering window'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='pump_duration',
            field=models.IntegerField(help_text='Active pump runtime in seconds (also the per-action duration when scheduling)'),
        ),
    ]
